# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia la carpeta del proyecto completa
COPY PracticaAPI/ ./PracticaAPI/

# Cambiar al directorio del proyecto
WORKDIR /app/PracticaAPI

# Restaurar paquetes NuGet
RUN dotnet restore

# Publicar en modo Release
RUN dotnet publish -c Release -o /app/out

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copiar los archivos publicados
COPY --from=build /app/out .

# Ejecutar la aplicación
ENTRYPOINT ["dotnet", "PracticaAPI.dll"]
